#!/bin/sh
#
# Simple shell script to generate documentation
#

if [ `whoami` = 'zapotek' ]; then
    outdir='-o /home/zapotek/workspace/arachni-gh-pages/'

    inkscape gfx/logo.svg --export-png=/home/zapotek/workspace/arachni-gh-pages/logo.png
    inkscape gfx/icon.svg --export-png=/home/zapotek/workspace/arachni-gh-pages/icon.png
    inkscape gfx/icon.svg --export-png=/home/zapotek/workspace/arachni-gh-pages/favicon.ico
    inkscape gfx/banner.svg --export-png=/home/zapotek/workspace/arachni-gh-pages/banner.png
    
fi

yardoc --verbose --protected --title \
  "Arachni - Web Application Security Scanner Framework" reports/* modules/* lib/* \
  $outdir \
  - LICENSE.md AUTHORS.md ACKNOWLEDGMENTS.md DIAGRAMS.md HACKING.md CHANGELOG.md \
  CONTRIBUTORS.md

rm -rf .yard*
