#!/bin/sh
# $Id$
#
# Simple shell script to generate documentation
#
yardoc --verbose --protected --private --title \
"Arachni - Web Application Vulnerability Scanning Framework" reports/* modules/* lib/* \
  - LICENSE AUTHORS TODO ACKNOWLEDGMENTS DIAGRAMS.md HACKING.md
  
  